# Generated by Django 5.2.8 on 2025-11-23 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=100)),
                ('color', models.CharField(choices=[('#FF0000', 'Red'), ('#0000FF', 'Blue'), ('#00FF00', 'Green'), ('#FFFF00', 'Yellow'), ('#800080', 'Purple'), ('#FFA500', 'Orange'), ('#FFC0CB', 'Pink'), ('#008080', 'Teal'), ('#A52A2A', 'Brown'), ('#808080', 'Gray'), ('#000000', 'Black'), ('#00FFFF', 'Cyan')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='MonthBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month_budget', models.DateField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('month_budget',), name='unique_month_budget')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.category')),
            ],
            options={
                'unique_together': {('category', 'month')},
            },
        ),
    ]
