# Generated by Django 5.2.8 on 2026-09-09 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_transaction_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthbudget',
            name='unique_month_budget',
        ),
        migrations.AddConstraint(
            model_name='monthbudget',
            constraint=models.UniqueConstraint(fields=('user', 'month_budget'), name='unique_user_month_budget'),
        ),
    ]
